sudo: false

language: python

python:
- "3.3"
- "3.4"
- "3.5"

env:
  global:
  - REDIS_PORT_1=6379
  - REDIS_PORT_2=6380
  - REDIS_SOCKET=/tmp/aioredis.sock
  matrix:
  - REDIS_TAG=2.6.17
  - REDIS_TAG=2.8.22
  - REDIS_TAG=3.0.4

cache:
  directories:
  - $HOME/redis-$REDIS_TAG
  - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
- export REDIS_BIN=$HOME/redis-${REDIS_TAG}/bin
- >
  if [ ! -x "$REDIS_BIN/redis-server" ]; then
    wget -c https://github.com/antirez/redis/archive/${REDIS_TAG}.tar.gz -O redis-${REDIS_TAG}.tar.gz
    tar -xvf redis-${REDIS_TAG}.tar.gz
    cd redis-${REDIS_TAG}
    make && make PREFIX=$HOME/redis-${REDIS_TAG} install
  fi

install:
- pip install hiredis
- pip install pyflakes
- pip install pep8
- pip install coverage
- pip install coveralls
- pip install -e .

before_script:
# main redis instance listening port & socket
- >
  $REDIS_BIN/redis-server --daemonize yes
  --pidfile ./redis-server.pid
  --unixsocket $REDIS_SOCKET
  --port $REDIS_PORT_1
  --save ""
# second redis instance, yet for migrate command tests
- >
  $REDIS_BIN/redis-server --daemonize yes
  --pidfile ./redis-server-2.pid
  --port $REDIS_PORT_2
  --save ""
- sleep 3
- $REDIS_BIN/redis-cli -s $REDIS_SOCKET PING
- $REDIS_BIN/redis-cli -p $REDIS_PORT_2 PING
- export REDIS_VERSION="$(redis-cli -s $REDIS_SOCKET INFO SERVER | sed -n 2p)"
- echo $REDIS_VERSION

script:
- pyflakes aioredis tests
- pep8 aioredis tests
- python runtests.py --coverage -v

# checking examples
- >
  for example in $(find $PWD/examples/ -name "*.py"); do
    echo "Running ${example}";
    python3 ${example} || exit 1;
  done;

after_script:
- coveralls
