sudo: false
dist: trusty

language: python

addons:
  apt:
    packages:
    - socat
    - enchant
    - aspell
    - aspell-en

env:
  global:
  - REDIS_TAGS="2.6.17 2.8.22 3.0.7 3.2.6 4.0-rc2" INSTALL_DIR=$HOME/redis

matrix:
  include:
  - python: "3.3"
    env: TASKS="ci-test flake examples"
  - python: "3.4"
    env: TASKS="ci-test flake examples"
  - python: "3.5"
    env: TASKS="ci-test flake examples"
  - python: "3.6"
    env: TASKS="ci-test flake examples spelling"
  - python: "3.6"
    env: TASKS="ci-test flake examples" TEST_ARGS="--uvloop -v"
  - python: "pypy-5.3.1"
    env: PYPY_RELEASE="pypy3-v5.7.0-linux64" TASKS="ci-test examples"
  allow_failures:
  - env: TASKS="ci-test flake examples" TEST_ARGS="--uvloop -v"

cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
- make -j ci-build-redis
- |
    if [ "$TRAVIS_PYTHON_VERSION" = "pypy-5.3.1" ]; then
      wget -nv -c "https://bitbucket.org/pypy/pypy/downloads/$PYPY_RELEASE.tar.bz2" -O - | tar -xjC $HOME
      export PYPY_VERSION="$($HOME/$PYPY_RELEASE/bin/pypy3 -V | grep PyPy | cut -d ' ' -f2)"
      $HOME/$PYPY_RELEASE/bin/pypy3 -m venv --clear $HOME/virtualenvs/pypy3
      $HOME/$PYPY_RELEASE/bin/pypy3 -m venv $HOME/virtualenvs/pypy3
      source $HOME/virtualenvs/pypy3/bin/activate
      python --version
    fi
- pip install -r tests/requirements.txt
- pip install -r docs/requirements.txt
- pip install -e .
- |
    for ARG in $TEST_ARGS; do
      if [ "$ARG" = "--uvloop" ]; then
        pip install uvloop
      fi;
    done

script:
- make $TASKS

after_script:
- codecov
