language: python

python:
- "3.3"
- "3.4"

before_install:
- sudo add-apt-repository -y ppa:chris-lea/redis-server
- sudo apt-get update -qq
- sudo apt-get install redis-server
- redis-server --version

install:
- pip install hiredis
- pip install pyflakes
- pip install pep8
- pip install coverage
- pip install -e .

env:
  global:
  - REDIS_PORT_1=6379 REDIS_PORT_2=6380 REDIS_SOCKET=/tmp/aioredis.sock REDIS_PATH_PREFIX=""
  matrix:
  - REDIS_TARGET="2.6"
  - REDIS_TARGET="2.8"

before_install:
- env
- >
  if [ $REDIS_TARGET = "2.6" ]; then
    wget http://download.redis.io/releases/redis-2.6.17.tar.gz
    tar xzf redis-2.6.17.tar.gz
    cd redis-2.6.17
    make
    export REDIS_PATH_PREFIX="$(pwd)/src/"
    cd ..
  fi

before_script:
# main redis instance listening port & socket
- >
  ${REDIS_PATH_PREFIX}redis-server --daemonize yes
  --pidfile ./redis-server.pid
  --unixsocket $REDIS_SOCKET
  --port $REDIS_PORT_1
  --save ""
# second redis instance, yet for migrate command tests
- >
  ${REDIS_PATH_PREFIX}redis-server --daemonize yes
  --pidfile ./redis-server-2.pid
  --port $REDIS_PORT_2
  --save ""
- sleep 3
- ${REDIS_PATH_PREFIX}redis-cli -s $REDIS_SOCKET PING
- ${REDIS_PATH_PREFIX}redis-cli -p $REDIS_PORT_2 PING
# set redis instance version for tests
- export REDIS_VERSION="$(redis-cli -s $REDIS_SOCKET INFO SERVER | sed -n 2p)"

script:
- pyflakes aioredis tests
- pep8 aioredis tests
- python runtests.py --coverage -v

# checking examples
- >
  for example in $(find $PWD/examples/ -name "*.py"); do
  echo "Running ${example}";
  python3 ${example} || exit 1;
  done;
