sudo: false

addons:
  apt:
    packages:
    - socat
    - enchant
    - aspell
    - aspell-en

language: python

env:
  global:
  - REDIS_TAGS="2.6.17 2.8.22 3.0.7 3.2.6 4.0-rc2" CERT_DIR=/tmp/certs INSTALL_DIR=$HOME/redis TEST_ARGS=-q

matrix:
  include:
  - python: "3.3"
    env: TASKS="flake examples"
  - python: "3.4"
    env: TASKS="flake examples"
  - python: "3.5"
    env: TASKS="flake examples spelling"
  - python: "3.6"
    env: TASKS="flake examples"
  - python: "3.6"
    env: TEST_ARGS="-q --uvloop"
  allow_failures:
  - env: TEST_ARGS="-q --uvloop"

cache: pip
#   directories:
#   - $HOME/redis
#   - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
- pip install hiredis
- pip install sphinx
- pip install codecov
- pip install -r tests/requirements.txt
- pip install -r docs/requirements.txt
- pip install -e .
- >
  if [ "$TEST_ARGS" = "--uvloop" ]; then
    pip install uvloop
  fi

before_script:
# make certificate for ssl/tls test and build Redises
- make -j certificate ci-build-redis

script:
- make ci-test
- make $TASKS

after_script:
- codecov
