language: python

python:
- "3.3"
- "3.4"

services:
- redis-server

install:
- pip install hiredis
- pip install -e .

before_script:
# patch redis config
- sudo service redis-server stop
- sleep 3
- export REDIS_PORT=6379 REDIS_SOCKET=/tmp/aioredis.sock
- >
  redis-server --daemonize yes
  --pidfile ./redis-server.pid
  --unixsocket $REDIS_SOCKET
  --port $REDIS_PORT
  --save ""
- sleep 3
- redis-cli -s $REDIS_SOCKET PING

script:
- python runtests.py -v
