sudo: false

addons:
  apt:
    packages:
    - socat
    - enchant
    - aspell
    - aspell-en

language: python

python:
- "3.3"
- "3.4"
- "3.5"
- "3.6-dev"

env:
  global:
  - REDIS_TAGS="2.6.17 2.8.22 3.0.5 3.2.0" CERT_DIR=/tmp/certs

matrix:
  include:
  - python: 3.6-dev
    env: TEST_ARGS=--uvloop
  allow_failures:
  - env: TEST_ARGS=--uvloop

cache:
  directories:
  - $HOME/redis
  - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
- pip install hiredis
- pip install sphinx
- pip install codecov
- pip install -r tests/requirements.txt
- pip install -r docs/requirements.txt
- pip install -e .
- >
  if [ "$TEST_ARGS" = "--uvloop" ]; then
    pip install uvloop
  fi

before_script:
# make certificate for ssl/tls test and build Redises
- make certificate
- make ci-build-redis

script:
- make spelling
- make flake
- make ci-test INSTALL_DIR=$HOME/redis
- make examples

after_script:
- codecov
